@{
    RootModule            = 'GitHub.psm1'
    ModuleVersion         = '0.36.0'
    CompatiblePSEditions  = @(
        'Core'
        'Desktop'
    )
    GUID                  = '200c3c9a-b6a4-418f-972c-2ab11cf5b351'
    Author                = 'PSModule'
    CompanyName           = 'PSModule'
    Copyright             = '(c) 2025 PSModule. All rights reserved.'
    Description           = 'A PowerShell module to interact with GitHub, both interactively and via automation.'
    PowerShellVersion     = '5.1'
    ProcessorArchitecture = 'None'
    RequiredModules       = @(
        @{
            ModuleName      = 'CasingStyle'
            RequiredVersion = '1.0.2'
        }
        @{
            ModuleName      = 'Context'
            RequiredVersion = '8.1.0'
        }
        @{
            ModuleName      = 'Hashtable'
            RequiredVersion = '1.1.6'
        }
        @{
            ModuleName      = 'Sodium'
            RequiredVersion = '2.2.0'
        }
        @{
            ModuleName      = 'TimeSpan'
            RequiredVersion = '3.0.1'
        }
        @{
            ModuleName      = 'Uri'
            RequiredVersion = '1.1.2'
        }
    )
    TypesToProcess        = @(
        'types/GitHubArtifact.Types.ps1xml'
        'types/GitHubContext.Types.ps1xml'
        'types/GitHubEnvironment.Types.ps1xml'
        'types/GitHubNode.Types.ps1xml'
        'types/GitHubOrganization.Types.ps1xml'
        'types/GitHubOwner.Types.ps1xml'
        'types/GitHubRateLimitResource.Types.ps1xml'
        'types/GitHubRelease.Types.ps1xml'
        'types/GitHubRepository.Types.ps1xml'
        'types/GitHubTeam.Types.ps1xml'
        'types/GitHubUser.Types.ps1xml'
        'types/GitHubWorkflow.Types.ps1xml'
        'types/GitHubWorkflowRun.Types.ps1xml'
    )
    FormatsToProcess      = @(
        'formats/GitHubAppInstallation.Format.ps1xml'
        'formats/GitHubArtifact.Format.ps1xml'
        'formats/GitHubConfig.Format.ps1xml'
        'formats/GitHubContext.Format.ps1xml'
        'formats/GitHubEnvironment.Format.ps1xml'
        'formats/GitHubLicense.Format.ps1xml'
        'formats/GitHubOwner.Format.ps1xml'
        'formats/GitHubPlan.Format.ps1xml'
        'formats/GitHubRateLimitResource.Format.ps1xml'
        'formats/GitHubRelease.Format.ps1xml'
        'formats/GitHubReleaseAsset.Format.ps1xml'
        'formats/GitHubRepository.Format.ps1xml'
        'formats/GitHubSecret.Format.ps1xml'
        'formats/GitHubTeam.Format.ps1xml'
        'formats/GitHubVariable.Format.ps1xml'
        'formats/GitHubWebhookDelivery.Format.ps1xml'
        'formats/GitHubWorkflow.Format.ps1xml'
        'formats/GitHubWorkflowRun.Format.ps1xml'
    )
    FunctionsToExport     = @(
        'Add-GitHubAppInstallationRepositoryAccess'
        'Add-GitHubMask'
        'Add-GitHubReleaseAsset'
        'Add-GitHubSecretSelectedRepository'
        'Add-GitHubSystemPath'
        'Add-GitHubUserEmail'
        'Add-GitHubUserFollowing'
        'Add-GitHubUserGpgKey'
        'Add-GitHubUserKey'
        'Add-GitHubUserSigningKey'
        'Add-GitHubUserSocial'
        'Add-GitHubVariableSelectedRepository'
        'Block-GitHubUser'
        'Connect-GitHubAccount'
        'Connect-GitHubApp'
        'ConvertFrom-IssueForm'
        'Disable-GitHubCommand'
        'Disable-GitHubRepositoryPrivateVulnerabilityReporting'
        'Disable-GitHubRepositorySecurityFix'
        'Disable-GitHubRepositoryVulnerabilityAlert'
        'Disable-GitHubWorkflow'
        'Disconnect-GitHubAccount'
        'Enable-GitHubCommand'
        'Enable-GitHubRepositoryPrivateVulnerabilityReporting'
        'Enable-GitHubRepositorySecurityFix'
        'Enable-GitHubRepositoryVulnerabilityAlert'
        'Enable-GitHubWorkflow'
        'Export-GitHubVariable'
        'Get-GitHubAccessToken'
        'Get-GitHubApiVersion'
        'Get-GitHubApp'
        'Get-GitHubAppAccessibleRepository'
        'Get-GitHubAppInstallation'
        'Get-GitHubAppInstallationRepositoryAccess'
        'Get-GitHubAppInstallationRequest'
        'Get-GitHubAppWebhookConfiguration'
        'Get-GitHubAppWebhookDelivery'
        'Get-GitHubArtifact'
        'Get-GitHubBlockedUser'
        'Get-GitHubConfig'
        'Get-GitHubContext'
        'Get-GitHubEmoji'
        'Get-GitHubEnterprise'
        'Get-GitHubEnterpriseOrganization'
        'Get-GitHubEnvironment'
        'Get-GitHubEventData'
        'Get-GitHubGitConfig'
        'Get-GitHubGitignore'
        'Get-GitHubLicense'
        'Get-GitHubMarkdown'
        'Get-GitHubMarkdownRaw'
        'Get-GitHubMeta'
        'Get-GitHubOctocat'
        'Get-GitHubOrganization'
        'Get-GitHubOrganizationMember'
        'Get-GitHubOrganizationPendingInvitation'
        'Get-GitHubOutput'
        'Get-GitHubPublicKey'
        'Get-GitHubRateLimit'
        'Get-GitHubRelease'
        'Get-GitHubReleaseAsset'
        'Get-GitHubRepository'
        'Get-GitHubRepositoryActivity'
        'Get-GitHubRepositoryAutolink'
        'Get-GitHubRepositoryCodeownersError'
        'Get-GitHubRepositoryContributor'
        'Get-GitHubRepositoryCustomProperty'
        'Get-GitHubRepositoryFork'
        'Get-GitHubRepositoryLanguage'
        'Get-GitHubRepositoryPermission'
        'Get-GitHubRepositoryRuleSuite'
        'Get-GitHubRepositorySecurityFix'
        'Get-GitHubRepositoryTag'
        'Get-GitHubRepositoryTeam'
        'Get-GitHubRepositoryTopic'
        'Get-GitHubRoot'
        'Get-GitHubRunnerData'
        'Get-GitHubScheduledMaintenance'
        'Get-GitHubSecret'
        'Get-GitHubSecretSelectedRepository'
        'Get-GitHubStatus'
        'Get-GitHubStatusComponent'
        'Get-GitHubStatusIncident'
        'Get-GitHubTeam'
        'Get-GitHubUser'
        'Get-GitHubUserEmail'
        'Get-GitHubUserFollower'
        'Get-GitHubUserFollowing'
        'Get-GitHubUserGpgKey'
        'Get-GitHubUserKey'
        'Get-GitHubUserSigningKey'
        'Get-GitHubVariable'
        'Get-GitHubVariableSelectedRepository'
        'Get-GitHubViewer'
        'Get-GitHubWorkflow'
        'Get-GitHubWorkflowRun'
        'Get-GitHubZen'
        'Install-GitHubApp'
        'Invoke-GitHubAPI'
        'Invoke-GitHubAppWebhookReDelivery'
        'Invoke-GitHubGraphQLQuery'
        'Move-GitHubRepository'
        'New-GitHubOrganization'
        'New-GitHubOrganizationInvitation'
        'New-GitHubRelease'
        'New-GitHubReleaseNote'
        'New-GitHubRepository'
        'New-GitHubRepositoryAutolink'
        'New-GitHubTeam'
        'New-GitHubVariable'
        'Remove-GitHubAppInstallationRepositoryAccess'
        'Remove-GitHubArtifact'
        'Remove-GitHubConfig'
        'Remove-GitHubEnvironment'
        'Remove-GitHubOrganization'
        'Remove-GitHubOrganizationInvitation'
        'Remove-GitHubRelease'
        'Remove-GitHubReleaseAsset'
        'Remove-GitHubRepository'
        'Remove-GitHubRepositoryAutolink'
        'Remove-GitHubRepositoryPermission'
        'Remove-GitHubSecret'
        'Remove-GitHubSecretSelectedRepository'
        'Remove-GitHubTeam'
        'Remove-GitHubUserEmail'
        'Remove-GitHubUserFollowing'
        'Remove-GitHubUserGpgKey'
        'Remove-GitHubUserKey'
        'Remove-GitHubUserSigningKey'
        'Remove-GitHubUserSocial'
        'Remove-GitHubVariable'
        'Remove-GitHubVariableSelectedRepository'
        'Remove-GitHubWorkflowRun'
        'Reset-GitHubConfig'
        'Reset-GitHubOutput'
        'Restart-GitHubWorkflowRun'
        'Revoke-GitHubAccessToken'
        'Save-GitHubArtifact'
        'Save-GitHubReleaseAsset'
        'Set-GitHubConfig'
        'Set-GitHubEnvironment'
        'Set-GitHubEnvironmentVariable'
        'Set-GitHubGitConfig'
        'Set-GitHubLogGroup'
        'Set-GitHubNoCommandGroup'
        'Set-GitHubOutput'
        'Set-GitHubRelease'
        'Set-GitHubRepository'
        'Set-GitHubRepositoryPermission'
        'Set-GitHubRepositoryTopic'
        'Set-GitHubSecret'
        'Set-GitHubSecretSelectedRepository'
        'Set-GitHubStepSummary'
        'Set-GitHubVariable'
        'Set-GitHubVariableSelectedRepository'
        'Start-GitHubLogGroup'
        'Start-GitHubRepositoryEvent'
        'Start-GitHubWorkflow'
        'Stop-GitHubLogGroup'
        'Stop-GitHubWorkflowRun'
        'Switch-GitHubContext'
        'Test-GitHubBlockedUser'
        'Test-GitHubRepositoryVulnerabilityAlert'
        'Test-GitHubUserFollowing'
        'Test-GitHubWebhookSignature'
        'Unblock-GitHubUser'
        'Uninstall-GitHubApp'
        'Update-GitHubAppInstallationRepositoryAccess'
        'Update-GitHubAppWebhookConfiguration'
        'Update-GitHubOrganization'
        'Update-GitHubRelease'
        'Update-GitHubReleaseAsset'
        'Update-GitHubRepository'
        'Update-GitHubTeam'
        'Update-GitHubUser'
        'Update-GitHubUserEmailVisibility'
        'Update-GitHubVariable'
        'Write-GitHubDebug'
        'Write-GitHubError'
        'Write-GitHubLog'
        'Write-GitHubNotice'
        'Write-GitHubWarning'
    )
    CmdletsToExport       = @()
    VariablesToExport     = @()
    AliasesToExport       = @(
        'Add-GitHubUserSocials'
        'Add-Mask'
        'Cancel-GitHubWorkflowRun'
        'Connect-GitHub'
        'Debug'
        'Disable-GitHubRepositorySecurityFixes'
        'Disable-GitHubRepositoryVulnerabilityAlerts'
        'Disconnect-GitHub'
        'Enable-GitHubRepositorySecurityFixes'
        'Enable-GitHubRepositoryVulnerabilityAlerts'
        'Error'
        'Follow-GitHubUser'
        'Generate-GitHubReleaseNotes'
        'Get-GitHubOwner'
        'Get-GitHubRepositoryAutolinks'
        'Get-GitHubRepositoryCustomProperties'
        'Get-GitHubRepositoryLanguages'
        'Get-GitHubRepositoryTags'
        'Get-GitHubRepositoryTeams'
        'Get-GitHubStatusComponents'
        'Get-GitHubStatusIncidents'
        'Log'
        'LogGroup'
        'Mask'
        'New-GitHubReleaseNotes'
        'New-GitHubSecret'
        'NoLogGroup'
        'Notice'
        'Redeliver-GitHubAppWebhookDelivery'
        'Remove-GitHubUserSocials'
        'Start-LogGroup'
        'Stop-LogGroup'
        'Summary'
        'Test-GitHubRepositoryVulnerabilityAlerts'
        'Test-GitHubUserFollows'
        'Unfollow-GitHubUser'
        'Warning'
    )
    ModuleList            = @()
    FileList              = @(
        'formats/GitHubAppInstallation.Format.ps1xml'
        'formats/GitHubArtifact.Format.ps1xml'
        'formats/GitHubConfig.Format.ps1xml'
        'formats/GitHubContext.Format.ps1xml'
        'formats/GitHubEnvironment.Format.ps1xml'
        'formats/GitHubLicense.Format.ps1xml'
        'formats/GitHubOwner.Format.ps1xml'
        'formats/GitHubPlan.Format.ps1xml'
        'formats/GitHubRateLimitResource.Format.ps1xml'
        'formats/GitHubRelease.Format.ps1xml'
        'formats/GitHubReleaseAsset.Format.ps1xml'
        'formats/GitHubRepository.Format.ps1xml'
        'formats/GitHubSecret.Format.ps1xml'
        'formats/GitHubTeam.Format.ps1xml'
        'formats/GitHubVariable.Format.ps1xml'
        'formats/GitHubWebhookDelivery.Format.ps1xml'
        'formats/GitHubWorkflow.Format.ps1xml'
        'formats/GitHubWorkflowRun.Format.ps1xml'
        'GitHub.psm1'
        'types/GitHubArtifact.Types.ps1xml'
        'types/GitHubContext.Types.ps1xml'
        'types/GitHubEnvironment.Types.ps1xml'
        'types/GitHubNode.Types.ps1xml'
        'types/GitHubOrganization.Types.ps1xml'
        'types/GitHubOwner.Types.ps1xml'
        'types/GitHubRateLimitResource.Types.ps1xml'
        'types/GitHubRelease.Types.ps1xml'
        'types/GitHubRepository.Types.ps1xml'
        'types/GitHubTeam.Types.ps1xml'
        'types/GitHubUser.Types.ps1xml'
        'types/GitHubWorkflow.Types.ps1xml'
        'types/GitHubWorkflowRun.Types.ps1xml'
    )
    PrivateData           = @{
        PSData = @{
            Tags       = @(
                'GitHub'
                'Linux'
                'MacOS'
                'PSEdition_Core'
                'PSEdition_Desktop'
                'PSModule'
                'Windows'
            )
            LicenseUri = 'https://github.com/PSModule/GitHub/blob/main/LICENSE'
            ProjectUri = 'https://github.com/PSModule/GitHub'
            IconUri    = 'https://raw.githubusercontent.com/PSModule/GitHub/main/icon/icon.png'
            Prerelease = 'kvSigning001'
        }
    }
}
